<%@ page language="java" pageEncoding="UTF-8"%>
<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html lang="en-US" ng-app="templeApp">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>วัดเจดีย์หลวง</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="bower_components/html5-boilerplate/css/normalize.css">
    <link rel="stylesheet" href="bower_components/html5-boilerplate/css/main.css">
    <link rel="stylesheet" href="app.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="css/foundation.min.css">
    <link rel="stylesheet" href="css/ie8-grid-foundation-4.css">
    <link rel="stylesheet" href="css/ie-fixes.css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/stylesheet.css">
    <link rel="stylesheet" href="css/superfish.css">
    <link rel="stylesheet" href="css/colorbox.css">
    <link rel="stylesheet" href="css/flexcar.css">
    <link rel="stylesheet" href="css/flexslider.css">
    <link rel="stylesheet" href="css/lightbox.css">

    <script src="bower_components/html5-boilerplate/js/vendor/modernizr-2.6.2.min.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-file-upload/angular-file-upload-shim.js"></script>
    <script src="bower_components/angular-file-upload/angular-file-upload.min.js"></script>
    <script src="app.js"></script>
   <script src="js/colorbox/jquery.colorbox-min.js"></script>
    <script src="js/slider/jquery.flexslider.js"></script>
    <script src="js/vendor/custom.modernizr.js"></script>
<!--     <script src="js/lightbox/prototype.js" ></script>!-->

    <script src="js/userController.js"></script>
    <script src="js/securityController.js"></script>
    <script src="js/userService.js"></script>
    <script src="js/historyController.js"></script>
    <script src="js/historyService.js"></script>
    <script src="js/galleryController.js"></script>
    <script src="js/galleryService.js"></script>
    <script src="js/contactController.js"></script>
    <script src="js/contactService.js"></script>
    <script src="js/questionController.js"></script>
    <script src="js/questionService.js"></script>
    <script src="js/newsController.js"></script>
    <script src="js/newsService.js"></script>

    <script src="bower_components/ng-flow/dist/ng-flow-standalone.js"></script>
    <script src="bower_components/angular-cookies/angular-cookies.js"></script>
    <script src ="bower_components/angular-translate/angular-translate.js"></script>
    <script src ="bower_components/angular-translate-loader-url/angular-translate-loader-url.js"></script>

    <style>
        /* Generated by Font Squirrel (http://www.fontsquirrel.com) on May 15, 2015 */
    .fontnav{
     color: #ffffff;
        font-size: 15px;
    }
        .page-header{
    height: 220px;
            position: relative;
            top: 5px;
        }
        .account{
            position: absolute;
            top: 140px;
            right: 20px;
        }
         .myButton {
             -moz-box-shadow:inset 0px 1px 0px 0px #d1d1d1;
             -webkit-box-shadow:inset 0px 1px 0px 0px #d1d1d1;
             box-shadow:inset 0px 1px 0px 0px #d1d1d1;
             background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #c7c7c7), color-stop(1, #dbdbdb));
             background:-moz-linear-gradient(top, #c7c7c7 5%, #dbdbdb 100%);
             background:-webkit-linear-gradient(top, #c7c7c7 5%, #dbdbdb 100%);
             background:-o-linear-gradient(top, #c7c7c7 5%, #dbdbdb 100%);
             background:-ms-linear-gradient(top, #c7c7c7 5%, #dbdbdb 100%);
             background:linear-gradient(to bottom, #c7c7c7 5%, #dbdbdb 100%);
             filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#c7c7c7', endColorstr='#dbdbdb',GradientType=0);
             background-color:#c7c7c7;
             border:1px solid #b5b5b5;
             display:inline-block;
             cursor:pointer;
             color:#000000;
             font-family:Arial;
             font-size:12px;
             font-weight:bold;
             padding:3px 20px;
             text-decoration:none;
         }
        .myButton:hover {
            background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #dbdbdb), color-stop(1, #c7c7c7));
            background:-moz-linear-gradient(top, #dbdbdb 5%, #c7c7c7 100%);
            background:-webkit-linear-gradient(top, #dbdbdb 5%, #c7c7c7 100%);
            background:-o-linear-gradient(top, #dbdbdb 5%, #c7c7c7 100%);
            background:-ms-linear-gradient(top, #dbdbdb 5%, #c7c7c7 100%);
            background:linear-gradient(to bottom, #dbdbdb 5%, #c7c7c7 100%);
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dbdbdb', endColorstr='#c7c7c7',GradientType=0);
            background-color:#dbdbdb;
        }
        .myButton:active {
            position:relative;
            top:1px;
        }



    </style>

</head>
<body>

<div class="page-header" style="background-color: transparent; background: url(picture/head.png)" >
    <div class="row">
                <table class="account" style="background: transparent; border: 0px" ng-show="hasRole('admin')||hasRole('registered user')" >
                    <tr>
                        <td style="color: #ffffff">ยินดีต้อนรับคุณ</td>
                        <td style="color: #ffffff">{{Loguser.f_name}} {{Loguser.l_name}}</td>
                    </tr>
                    <tr style="background: transparent">
                        <td colspan="2" style="background: transparent" align="right">
                            <a href="#/setting" class="myButton" ng-hide="hasRole('admin')">ตั้งค่า</a>
                        <a ng-click="logOut()" class="myButton">ออกจากระบบ</a> </td>
                    </tr>
                 </table>
        <table class="account" style="background: transparent; border: 0px" ng-hide="hasRole('admin')||hasRole('registered user')">
            <tr style="background: transparent">
                <td style="background: transparent" align="right">
                    <a href="#/Loginpage" class="myButton" >ล็อกอิน</a>
            </tr>
        </table>
    <div class="col-md-11" >
    <div role="navigation" >
    <nav class="nav nav-pills nav-justified" style="padding-top: 180px" >
            <div class="collapse navbar-collapse" align="center" >
                    <ul class="nav navbar-nav" style="top: 100px">
                    <li class="nav" ng-class="{true: 'active'}[menuActive('/Homepage')]">
                        <a  href="#/Homepage"><p class="fontnav">หน้าแรก</p></a>
                    </li>
                    <li ng-class="{true: 'active'}[menuActive('/Newspage')]">
                        <a  href="#/Newspage"><p class="fontnav">ข่าวสาร</p></a>
                    </li>
                    <li ng-class="{true: 'active'}[menuActive('/Historypage')]">
                        <a href="#/Historypage"><p class="fontnav">ประวัติ</p></a>
                    </li>
                    <li ng-class="{true: 'active'}[menuActive('/Questionpage')]" ng-hide="hasRole('admin')">
                        <a  href="#/Questionpage"><p class="fontnav">ถาม-ตอบธรรมะ</p></a>
                    </li>
                        <li ng-class="{true: 'active'}[menuActive('/Questionpage')]" ng-show="hasRole('registered user')">
                            <a  href="#/OwnQuestionpage"><p class="fontnav">คำถามส่วนตัว</p></a>
                        </li>
                        <li ng-class="{true: 'active'}[menuActive('/Questionpage')]" ng-show="hasRole('admin')">
                            <a  href="#/Answerpage"><p class="fontnav">ตอบธรรมะ</p></a>
                        </li>
                    <li ng-class="{true: 'active'}[menuActive('/Gallerypage')]">
                        <a  href="#/Gallerypage"><p class="fontnav">แกลอรี่</p></a>
                    </li>
                    <li ng-class="{true: 'active'}[menuActive('/Mappage')]">
                        <a  href="#/Mappage"><p class="fontnav">แผนที่</p></a>
                    </li>
                    <li ng-class="{true: 'active'}[menuActive('/Contactpage')]">
                        <a  href="#/Contactpage"><p class="fontnav">ติดต่อวัด</p></a>
                    </li>

                </ul>
        </div>

</nav>
    </div>
</div>
</div>
    </div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
            <!-- Breadcrumbs
           ================================================== -->
            <ng-view>Loading...</ng-view>

        </div>
    </div>
</div>

</body>
<footer>
    <div>
        <div class="columns large-11 credit" style="background-color: #161616"> &copy; College of Arts, Media and Technology Chiang Mai University Design by: PowerPuff Girls w/ Proposal
        </div>

    </div>


</footer>
</html>
